M48
; DRILL file {KiCad (6.0.2)} date Fri Apr  1 11:09:22 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-04-01T11:09:22+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1693
%
G90
G05
T1
X0.1969Y-0.1969
X0.1969Y-3.7402
X2.1654Y-0.1969
X2.1654Y-1.9685
X2.1654Y-3.7402
T0
M30
